# Generated by Django 5.2.11 on 2026-02-24 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Refuge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Territoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=5, unique=True, verbose_name='Code Postal')),
                ('department_code', models.CharField(db_index=True, max_length=3, verbose_name='Département')),
                ('ville', models.CharField(max_length=100, verbose_name='Nom de la Ville')),
                ('income_level', models.FloatField(default=0.0, verbose_name='Revenu Médian')),
                ('unemployment_rate', models.FloatField(default=0.0, verbose_name='Taux de Chômage')),
                ('sec_home_ratio', models.FloatField(default=0.0, verbose_name='Ratio Résidences Secondaires')),
                ('osm_details', models.JSONField(default=dict, verbose_name='Détails Services (Vétos, Parcs)')),
                ('risk_index', models.FloatField(default=0.0, verbose_name='Indice de Risque')),
                ('well_being_score', models.CharField(default='C', max_length=1, verbose_name='Note Bien-être')),
                ('score_factors', models.JSONField(default=list, verbose_name='Facteurs explicatifs')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilAdoptant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=5)),
                ('type_habitat', models.CharField(choices=[('APT', 'Appartement'), ('HOUSE', 'Maison')], max_length=20)),
                ('has_garden', models.BooleanField(default=False)),
                ('niv_activite', models.IntegerField(default=5, verbose_name="Niveau d'activité (1-10)")),
                ('has_children', models.BooleanField(default=False, verbose_name="Présence d'enfants")),
                ('has_pets', models.BooleanField(default=False, verbose_name='Autres animaux')),
                ('temps_dispo', models.IntegerField(default=2, verbose_name='Temps disponible (heures/jour)')),
                ('niv_experience', models.IntegerField(default=1, verbose_name='Expérience (1-3)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(choices=[('DOG', 'Chien'), ('CAT', 'Chat')], max_length=50)),
                ('race', models.CharField(blank=True, max_length=100)),
                ('age', models.IntegerField()),
                ('taille', models.CharField(choices=[('S', 'Petit'), ('M', 'Moyen'), ('L', 'Grand')], max_length=10)),
                ('energy_need', models.IntegerField(default=5)),
                ('social_compatibility', models.BooleanField(default=True)),
                ('kid_friendly', models.BooleanField(default=True)),
                ('needs_garden', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('is_adoptable', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='animals/')),
                ('refuge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animaux', to='api.refuge')),
            ],
        ),
    ]
