# Generated by Django 5.2.11 on 2026-03-24 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiladoptant',
            name='niv_activite',
            field=models.IntegerField(default=1, verbose_name="Niveau d'activité (1-3)"),
        ),
        migrations.AlterField(
            model_name='profiladoptant',
            name='type_habitat',
            field=models.CharField(choices=[('APT', 'Appartement'), ('HOUSE', 'Maison'), ('FARM', 'Ferme')], default='APT', max_length=20),
        ),
    ]
