# Generated by Django 5.2.11 on 2026-03-24 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_profiladoptant_niv_activite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='age_category',
            field=models.CharField(choices=[('puppy', 'Chiot'), ('adult', 'Adulte'), ('senior', 'Senior')], default='adult', max_length=10),
        ),
        migrations.AddField(
            model_name='profiladoptant',
            name='has_birds',
            field=models.BooleanField(default=False, verbose_name='Oiseaux'),
        ),
        migrations.AddField(
            model_name='profiladoptant',
            name='has_cats',
            field=models.BooleanField(default=False, verbose_name='Chats'),
        ),
        migrations.AddField(
            model_name='profiladoptant',
            name='has_dogs',
            field=models.BooleanField(default=False, verbose_name='Chiens'),
        ),
        migrations.AddField(
            model_name='profiladoptant',
            name='has_rodents',
            field=models.BooleanField(default=False, verbose_name='Rongeurs'),
        ),
    ]
