# Generated by Django 5.2.11 on 2026-03-27 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_animal_age_category_profiladoptant_has_birds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalSignaled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(choices=[('DOG', 'Chien'), ('CAT', 'Chat'), ('OTHER', 'Autre')], max_length=20)),
                ('race', models.CharField(blank=True, help_text='Si connue', max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='signalements/')),
                ('description', models.TextField(verbose_name='Description / État de santé')),
                ('adresse_approximative', models.CharField(help_text='Rue ou quartier', max_length=255)),
                ('type_signalement', models.CharField(choices=[('FOUND', 'J’ai trouvé un animal'), ('ABANDON', 'Je ne peux plus garder mon animal')], max_length=10)),
                ('status', models.CharField(choices=[('SIGNALED', 'Signalé'), ('RESCUED', 'Pris en charge (Refuge/Asso)'), ('ADOPTABLE', 'Ouvert à l’adoption')], default='SIGNALED', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal_adoption', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origine_signalement', to='api.animal')),
                ('territoire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements', to='api.territoire')),
            ],
        ),
    ]
