# Generated by Django 5.2.11 on 2026-03-29 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='territoire',
            name='latitude',
            field=models.FloatField(default=0.0, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='territoire',
            name='longitude',
            field=models.FloatField(default=0.0, verbose_name='Longitude'),
        ),
    ]
